/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVentasRouteImport } from './routes/app.ventas'
import { Route as AppUnidadesRouteImport } from './routes/app.unidades'
import { Route as AppTesoreriaRouteImport } from './routes/app.tesoreria'
import { Route as AppTercerosRouteImport } from './routes/app.terceros'
import { Route as AppSeguridadRouteImport } from './routes/app.seguridad'
import { Route as AppReportesRouteImport } from './routes/app.reportes'
import { Route as AppProductosRouteImport } from './routes/app.productos'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppNominaRouteImport } from './routes/app.nomina'
import { Route as AppMarcasRouteImport } from './routes/app.marcas'
import { Route as AppInventariosRouteImport } from './routes/app.inventarios'
import { Route as AppGeografiaRouteImport } from './routes/app.geografia'
import { Route as AppGastosRouteImport } from './routes/app.gastos'
import { Route as AppEmpresasRouteImport } from './routes/app.empresas'
import { Route as AppContabilidadRouteImport } from './routes/app.contabilidad'
import { Route as AppConfiguracionRouteImport } from './routes/app.configuracion'
import { Route as AppComprasRouteImport } from './routes/app.compras'
import { Route as AppCategoriasRouteImport } from './routes/app.categorias'
import { Route as AppBodegasRouteImport } from './routes/app.bodegas'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVentasRoute = AppVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AppRoute,
} as any)
const AppUnidadesRoute = AppUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AppRoute,
} as any)
const AppTesoreriaRoute = AppTesoreriaRouteImport.update({
  id: '/tesoreria',
  path: '/tesoreria',
  getParentRoute: () => AppRoute,
} as any)
const AppTercerosRoute = AppTercerosRouteImport.update({
  id: '/terceros',
  path: '/terceros',
  getParentRoute: () => AppRoute,
} as any)
const AppSeguridadRoute = AppSeguridadRouteImport.update({
  id: '/seguridad',
  path: '/seguridad',
  getParentRoute: () => AppRoute,
} as any)
const AppReportesRoute = AppReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AppRoute,
} as any)
const AppProductosRoute = AppProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppNominaRoute = AppNominaRouteImport.update({
  id: '/nomina',
  path: '/nomina',
  getParentRoute: () => AppRoute,
} as any)
const AppMarcasRoute = AppMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AppRoute,
} as any)
const AppInventariosRoute = AppInventariosRouteImport.update({
  id: '/inventarios',
  path: '/inventarios',
  getParentRoute: () => AppRoute,
} as any)
const AppGeografiaRoute = AppGeografiaRouteImport.update({
  id: '/geografia',
  path: '/geografia',
  getParentRoute: () => AppRoute,
} as any)
const AppGastosRoute = AppGastosRouteImport.update({
  id: '/gastos',
  path: '/gastos',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)
const AppContabilidadRoute = AppContabilidadRouteImport.update({
  id: '/contabilidad',
  path: '/contabilidad',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppComprasRoute = AppComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppBodegasRoute = AppBodegasRouteImport.update({
  id: '/bodegas',
  path: '/bodegas',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/app/bodegas': typeof AppBodegasRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/compras': typeof AppComprasRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/contabilidad': typeof AppContabilidadRoute
  '/app/empresas': typeof AppEmpresasRoute
  '/app/gastos': typeof AppGastosRoute
  '/app/geografia': typeof AppGeografiaRoute
  '/app/inventarios': typeof AppInventariosRoute
  '/app/marcas': typeof AppMarcasRoute
  '/app/nomina': typeof AppNominaRoute
  '/app/pos': typeof AppPosRoute
  '/app/productos': typeof AppProductosRoute
  '/app/reportes': typeof AppReportesRoute
  '/app/seguridad': typeof AppSeguridadRoute
  '/app/terceros': typeof AppTercerosRoute
  '/app/tesoreria': typeof AppTesoreriaRoute
  '/app/unidades': typeof AppUnidadesRoute
  '/app/ventas': typeof AppVentasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/app/bodegas': typeof AppBodegasRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/compras': typeof AppComprasRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/contabilidad': typeof AppContabilidadRoute
  '/app/empresas': typeof AppEmpresasRoute
  '/app/gastos': typeof AppGastosRoute
  '/app/geografia': typeof AppGeografiaRoute
  '/app/inventarios': typeof AppInventariosRoute
  '/app/marcas': typeof AppMarcasRoute
  '/app/nomina': typeof AppNominaRoute
  '/app/pos': typeof AppPosRoute
  '/app/productos': typeof AppProductosRoute
  '/app/reportes': typeof AppReportesRoute
  '/app/seguridad': typeof AppSeguridadRoute
  '/app/terceros': typeof AppTercerosRoute
  '/app/tesoreria': typeof AppTesoreriaRoute
  '/app/unidades': typeof AppUnidadesRoute
  '/app/ventas': typeof AppVentasRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/app/bodegas': typeof AppBodegasRoute
  '/app/categorias': typeof AppCategoriasRoute
  '/app/compras': typeof AppComprasRoute
  '/app/configuracion': typeof AppConfiguracionRoute
  '/app/contabilidad': typeof AppContabilidadRoute
  '/app/empresas': typeof AppEmpresasRoute
  '/app/gastos': typeof AppGastosRoute
  '/app/geografia': typeof AppGeografiaRoute
  '/app/inventarios': typeof AppInventariosRoute
  '/app/marcas': typeof AppMarcasRoute
  '/app/nomina': typeof AppNominaRoute
  '/app/pos': typeof AppPosRoute
  '/app/productos': typeof AppProductosRoute
  '/app/reportes': typeof AppReportesRoute
  '/app/seguridad': typeof AppSeguridadRoute
  '/app/terceros': typeof AppTercerosRoute
  '/app/tesoreria': typeof AppTesoreriaRoute
  '/app/unidades': typeof AppUnidadesRoute
  '/app/ventas': typeof AppVentasRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/api/chat'
    | '/app/bodegas'
    | '/app/categorias'
    | '/app/compras'
    | '/app/configuracion'
    | '/app/contabilidad'
    | '/app/empresas'
    | '/app/gastos'
    | '/app/geografia'
    | '/app/inventarios'
    | '/app/marcas'
    | '/app/nomina'
    | '/app/pos'
    | '/app/productos'
    | '/app/reportes'
    | '/app/seguridad'
    | '/app/terceros'
    | '/app/tesoreria'
    | '/app/unidades'
    | '/app/ventas'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/chat'
    | '/app/bodegas'
    | '/app/categorias'
    | '/app/compras'
    | '/app/configuracion'
    | '/app/contabilidad'
    | '/app/empresas'
    | '/app/gastos'
    | '/app/geografia'
    | '/app/inventarios'
    | '/app/marcas'
    | '/app/nomina'
    | '/app/pos'
    | '/app/productos'
    | '/app/reportes'
    | '/app/seguridad'
    | '/app/terceros'
    | '/app/tesoreria'
    | '/app/unidades'
    | '/app/ventas'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/api/chat'
    | '/app/bodegas'
    | '/app/categorias'
    | '/app/compras'
    | '/app/configuracion'
    | '/app/contabilidad'
    | '/app/empresas'
    | '/app/gastos'
    | '/app/geografia'
    | '/app/inventarios'
    | '/app/marcas'
    | '/app/nomina'
    | '/app/pos'
    | '/app/productos'
    | '/app/reportes'
    | '/app/seguridad'
    | '/app/terceros'
    | '/app/tesoreria'
    | '/app/unidades'
    | '/app/ventas'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ventas': {
      id: '/app/ventas'
      path: '/ventas'
      fullPath: '/app/ventas'
      preLoaderRoute: typeof AppVentasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/unidades': {
      id: '/app/unidades'
      path: '/unidades'
      fullPath: '/app/unidades'
      preLoaderRoute: typeof AppUnidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tesoreria': {
      id: '/app/tesoreria'
      path: '/tesoreria'
      fullPath: '/app/tesoreria'
      preLoaderRoute: typeof AppTesoreriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/terceros': {
      id: '/app/terceros'
      path: '/terceros'
      fullPath: '/app/terceros'
      preLoaderRoute: typeof AppTercerosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seguridad': {
      id: '/app/seguridad'
      path: '/seguridad'
      fullPath: '/app/seguridad'
      preLoaderRoute: typeof AppSeguridadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reportes': {
      id: '/app/reportes'
      path: '/reportes'
      fullPath: '/app/reportes'
      preLoaderRoute: typeof AppReportesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/productos': {
      id: '/app/productos'
      path: '/productos'
      fullPath: '/app/productos'
      preLoaderRoute: typeof AppProductosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nomina': {
      id: '/app/nomina'
      path: '/nomina'
      fullPath: '/app/nomina'
      preLoaderRoute: typeof AppNominaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marcas': {
      id: '/app/marcas'
      path: '/marcas'
      fullPath: '/app/marcas'
      preLoaderRoute: typeof AppMarcasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventarios': {
      id: '/app/inventarios'
      path: '/inventarios'
      fullPath: '/app/inventarios'
      preLoaderRoute: typeof AppInventariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/geografia': {
      id: '/app/geografia'
      path: '/geografia'
      fullPath: '/app/geografia'
      preLoaderRoute: typeof AppGeografiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gastos': {
      id: '/app/gastos'
      path: '/gastos'
      fullPath: '/app/gastos'
      preLoaderRoute: typeof AppGastosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empresas': {
      id: '/app/empresas'
      path: '/empresas'
      fullPath: '/app/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contabilidad': {
      id: '/app/contabilidad'
      path: '/contabilidad'
      fullPath: '/app/contabilidad'
      preLoaderRoute: typeof AppContabilidadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracion': {
      id: '/app/configuracion'
      path: '/configuracion'
      fullPath: '/app/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compras': {
      id: '/app/compras'
      path: '/compras'
      fullPath: '/app/compras'
      preLoaderRoute: typeof AppComprasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categorias': {
      id: '/app/categorias'
      path: '/categorias'
      fullPath: '/app/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bodegas': {
      id: '/app/bodegas'
      path: '/bodegas'
      fullPath: '/app/bodegas'
      preLoaderRoute: typeof AppBodegasRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBodegasRoute: typeof AppBodegasRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppComprasRoute: typeof AppComprasRoute
  AppConfiguracionRoute: typeof AppConfiguracionRoute
  AppContabilidadRoute: typeof AppContabilidadRoute
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppGastosRoute: typeof AppGastosRoute
  AppGeografiaRoute: typeof AppGeografiaRoute
  AppInventariosRoute: typeof AppInventariosRoute
  AppMarcasRoute: typeof AppMarcasRoute
  AppNominaRoute: typeof AppNominaRoute
  AppPosRoute: typeof AppPosRoute
  AppProductosRoute: typeof AppProductosRoute
  AppReportesRoute: typeof AppReportesRoute
  AppSeguridadRoute: typeof AppSeguridadRoute
  AppTercerosRoute: typeof AppTercerosRoute
  AppTesoreriaRoute: typeof AppTesoreriaRoute
  AppUnidadesRoute: typeof AppUnidadesRoute
  AppVentasRoute: typeof AppVentasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBodegasRoute: AppBodegasRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppComprasRoute: AppComprasRoute,
  AppConfiguracionRoute: AppConfiguracionRoute,
  AppContabilidadRoute: AppContabilidadRoute,
  AppEmpresasRoute: AppEmpresasRoute,
  AppGastosRoute: AppGastosRoute,
  AppGeografiaRoute: AppGeografiaRoute,
  AppInventariosRoute: AppInventariosRoute,
  AppMarcasRoute: AppMarcasRoute,
  AppNominaRoute: AppNominaRoute,
  AppPosRoute: AppPosRoute,
  AppProductosRoute: AppProductosRoute,
  AppReportesRoute: AppReportesRoute,
  AppSeguridadRoute: AppSeguridadRoute,
  AppTercerosRoute: AppTercerosRoute,
  AppTesoreriaRoute: AppTesoreriaRoute,
  AppUnidadesRoute: AppUnidadesRoute,
  AppVentasRoute: AppVentasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
